.. This (-*- rst -*-) format file contains commonly used link targets
   and name substitutions.  It may be included in many files,
   therefore it should only contain link targets and name
   substitutions.  Try grepping for "^\.\. _" to find plausible
   candidates for this list.

.. NOTE: reST targets are
   __not_case_sensitive__, so only one target definition is needed for
   nipy, NIPY, Nipy, etc...


.. Stanford

.. _cni: http://cni.stanford.edu
.. _sdr: http://sdr.stanford.edu
.. _sdr-purl: http://purl.stanford.edu/fn662rv4961

.. nbviewer

.. _nbviewer: http://nbviewer.ipython.org/github/arokem/MRS/blob/refactor-for-release/ipynb/index.ipynb

.. _terminal: https://terminal.com/tiny/W2DpoIgOnQ 

.. MRS-github
.. _mrs-github: http://github.com/cni/MRS
.. _download-zip: https://github.com/vistalab/life/zipball/master
.. _download-tar: https://github.com/cni/MRS/tarball/master
.. _github-releases: https://github.com/cni/MRS/releases


.. NIPY
.. _nipy: http://nipy.org
.. _nibabel: http://nipy.org/nibabel
.. _nitime: http://nipy.org/nitime
.. _nipype: http://nipy.org/nipype

.. Packaging
.. _neurodebian: http://neuro.debian.net
.. _neurodebian how to: http://neuro.debian.net/#how-to-use-this-repository
.. _pip: http://www.pip-installer.org/en/latest/
.. _easy_install: https://pypi.python.org/pypi/setuptools

.. Documentation tools
.. _graphviz: http://www.graphviz.org/
.. _Sphinx: http://sphinx.pocoo.org/
.. _`Sphinx reST`: http://sphinx.pocoo.org/rest.html
.. _reST: http://docutils.sourceforge.net/rst.html
.. _docutils: http://docutils.sourceforge.net

.. Other python projects
.. _numpy: http://numpy.scipy.org
.. _scipy: http://www.scipy.org
.. _ipython: http://ipython.scipy.org
.. _`ipython manual`: http://ipython.scipy.org/doc/manual/html
.. _matplotlib: http://matplotlib.sourceforge.net
.. _pythonxy: http://www.pythonxy.com
.. _ETS: http://code.enthought.com/projects/tool-suite.php
.. _`Enthought Tool Suite`: http://code.enthought.com/projects/tool-suite.php
.. _canopy: https://www.enthought.com/products/canopy
.. _anaconda: http://continuum.io/downloads
.. _python: http://www.python.org
.. _mayavi: http://mayavi.sourceforge.net/
.. _sympy: http://code.google.com/p/sympy/
.. _networkx: http://networkx.lanl.gov/
.. _setuptools: http://pypi.python.org/pypi/setuptools
.. _distribute: http://packages.python.org/distribute
.. _datapkg: http://okfn.org/projects/datapkg
.. _pytables: http://www.pytables.org
.. _python-vtk: http://www.vtk.org

